/**
 * The static map graph, plus the movement search the turn machine runs on it.
 *
 * nodes.json is generated by tools/generate-board.mjs but nothing here assumes
 * that: any file matching the schema works, including one traced off the real
 * physical board.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const DATA = join(dirname(fileURLToPath(import.meta.url)), '..', '..', 'data', 'nodes.json');

export function loadBoard(path = DATA) {
  const raw = JSON.parse(readFileSync(path, 'utf8'));
  return buildBoard(raw);
}

export function buildBoard(raw) {
  const byId = new Map(raw.nodes.map((n) => [n.id, n]));

  for (const n of raw.nodes) {
    for (const e of n.edges) {
      if (!byId.has(e.target)) {
        throw new Error(`board: ${n.id} has an edge to missing node ${e.target}`);
      }
    }
  }

  const cityIds = raw.nodes.filter((n) => n.type === 'city').map((n) => n.id);

  return {
    raw,
    byId,
    cityIds,
    homeCities: raw.homeCities ?? {},
    node: (id) => {
      const n = byId.get(id);
      if (!n) throw new Error(`board: unknown node ${id}`);
      return n;
    },
    isCity: (id) => byId.get(id)?.type === 'city',
    /** Nodes a player can fly to from here, ignoring how far they rolled. */
    flightTargets: (id) =>
      (byId.get(id)?.edges ?? []).filter((e) => e.type === 'flight').map((e) => e.target),
  };
}

/**
 * How many separate sea legs a path contains.
 *
 * The rulebook charges one beer "to begin the journey" (aloittaakseen matkan),
 * not one per water square, so a ferry hop broken up by connector dots must
 * still cost exactly one. We therefore count runs of consecutive water edges,
 * not water edges. See WATER_CHARGE_MODE in tokens.js.
 */
export function countWaterRuns(path) {
  let runs = 0;
  let inWater = false;
  for (const step of path) {
    if (step.type === 'water') {
      if (!inWater) runs++;
      inWater = true;
    } else {
      inWater = false;
    }
  }
  return runs;
}

/**
 * Every square reachable by moving 1..steps squares from `fromId`.
 *
 * Rules encoded here:
 *  - a team may move fewer squares than the die shows, so every intermediate
 *    square is a legal destination too;
 *  - a route may not double back through a square it has already used on that
 *    same branch (you cannot pad out a roll by stepping back and forth);
 *  - flight edges are not walkable - flying is a separate turn action costing
 *    three beers, not something a die roll pays for;
 *  - a route ends the moment it enters a border square. The guard at
 *    Haaparanta-Tornio stops you whether you wanted to stop or not.
 *
 * Returns Map<nodeId, { path, waterRuns, steps }>. Where several routes reach
 * the same square, the one chosen is the cheapest in sea legs and then the
 * shortest, so the server never bills a team for a ferry they could have avoided.
 */
export function findDestinations(board, fromId, steps) {
  const best = new Map();
  const origin = board.node(fromId);

  const walk = (nodeId, depth, visited, path, waterRuns) => {
    if (depth >= steps) return;

    for (const edge of board.node(nodeId).edges) {
      if (edge.type === 'flight') continue;
      if (visited.has(edge.target)) continue;

      const nextPath = [...path, { from: nodeId, to: edge.target, type: edge.type }];
      const nextWater = countWaterRuns(nextPath);
      const candidate = { path: nextPath, waterRuns: nextWater, steps: depth + 1 };

      const held = best.get(edge.target);
      if (!held || isCheaper(candidate, held)) best.set(edge.target, candidate);

      // A border square stops the team dead; the route cannot continue past it.
      if (board.node(edge.target).type === 'border') continue;

      visited.add(edge.target);
      walk(edge.target, depth + 1, visited, nextPath, nextWater);
      visited.delete(edge.target);
    }
  };

  walk(fromId, 0, new Set([origin.id]), [], 0);
  return best;
}

function isCheaper(a, b) {
  if (a.waterRuns !== b.waterRuns) return a.waterRuns < b.waterRuns;
  return a.steps < b.steps;
}

/** Shape sent to clients: paths as node-id lists, which is all the UI needs. */
export function serializeDestinations(destinations) {
  const out = {};
  for (const [id, d] of destinations) {
    out[id] = {
      steps: d.steps,
      waterRuns: d.waterRuns,
      waterEdges: d.path.filter((s) => s.type === 'water').length,
      path: [d.path[0].from, ...d.path.map((s) => s.to)],
    };
  }
  return out;
}
